base_url = "https://chariotsofiron.github.io"
title = "chariotsofiron"
compile_sass = true
generate_feed = true
taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true

[extra]
menu = [
    {name = "Tags", url = "/tags"},
    {name = "About", url = "/about"},
    {name = "Life stack", url = "/life-stack"},
]