base_url = "https://chariotsofiron.github.io"
title = "chariotsofiron"

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
github = "https://github.com/chariotsofiron"

mathjax = true
