# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: work around permission issue
        # https://github.com/actions/checkout/issues/760
        run: git config --global --add safe.directory /github/workspace
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: Zola Deploy to Pages
        uses: shalzz/zola-deploy-action@v0.12.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}